application: mizzazify
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/(.+)
  static_files: static/\1
  upload: static/.+

- url: /(img)?
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"
